site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Red Hat Display
  icon:
    logo: fontawesome/solid/b
  palette:
    scheme: default
    features:
      - navigation.footer

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
        emoji_index: materialx.emoji.twemoji
        emoji_generator: materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
      custom_fences
        - name: mermaid
          class: mermaid
          format: fenced_code_format

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/bstuder1

copyright: Copyright &copy; 2024 Brett Studer