site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Red Hat Display
  icon:
    logo: fontawesome/solid/b
  palette:
    scheme: default
    features:
      - navigation.footer

copyright: Copyright &copy; 2024 Brett Studer 