use_directory_urls: true
site_name: Brett Studer
site_url: https://brstuder.github.io/portfolio/
theme:
  name: material
  font:
    text: Google Sans Flex
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/b
  favicon: images/b.png
  palette:
    - scheme: slate #dark mode scheme
      primary: light blue
      accent: orange
      toggle:
        icon: material/lightbulb #light/dark mode button
        name: Switch to dark mode
    - scheme: default #light mode scheme
      primary: light blue
      accent: orange
      toggle:
        icon: material/lightbulb-outline #light/dark mode button
        name: Switch to dark mode
  features:
    - navigation.top           # "Back to top" button
    - navigation.footer        # Previous/next page links
    - content.code.copy         # Copy button for code blocks
    - content.code.annotate     # Enable code annotations

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.superfences
  - md_in_html
    # Content organization
  - pymdownx.tabbed:
      alternate_style: true
  # Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.smartsymbols
  - def_list
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page

extra_css:
  - /portfolio/stylesheets/style.css

plugins:
  - search #includes a search bar at the top of the page
  - callouts #used for adding context-specific note blocks into my content
  - tags #better cataloguing of all content

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bstuder1
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/brstuder
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:brett.studer99@gmail.com
      name: Email

nav:
  - Welcome: index.md
  - Kubecost:
      - Overview: kubecost/kubecost-overview.md
      - Writing Samples:
          - Budget API: kubecost/kubecost-samples/budget-api.md
          - Cloud Cost Trend API: kubecost/kubecost-samples/cloud-cost-trend-api.md
          - Network Monitoring: kubecost/kubecost-samples/network-monitoring.md
          - Efficiency and Idle: kubecost/kubecost-samples/efficiency-and-idle.md
          - Admission Controller: kubecost/kubecost-samples/admission-controller.md
          - Kubecost Cloud GCP Marketplace Licensing: kubecost/kubecost-samples/cloud-gcp-marketplace.md
          - Getting Highly Accurate and Granular Cost Metrics with Kubecost: kubecost/kubecost-samples/blog-getting-highly-accurate.md
      - Architecture Diagrams: kubecost/diagrams.md
  - MobiledgeX:
      - Overview: mobiledgex/mobiledgex.md
      - Writing Samples:
          - Manage GPU Drivers for Cloudlets: mobiledgex/edge-samples/manage-gpu-drivers-for-cloudlets.md
          - Mapping Virtual Machines to IaaS Resources: mobiledgex/edge-samples/mapping-virtual-machines.md 
          - Trust Policies: mobiledgex/edge-samples/trust-policy.md
      - Graphic Design: mobiledgex/design.md
  - Other Roles:
      - Arine: arine.md
      - AbbVie: abbvie.md
      - OpenMRS: openmrs.md
  - Portfolio Projects:
      - Audubon API: projects/audubon-api.md
      - Mkdocs Demo: projects/mkdocs-demo.md
  - About Me: about.md

copyright: Copyright &copy; 2025 Brett Studer 