site_name: Brett Studer
site_url: https://brettstuder.com/portfolio
theme:
  name: material
  font:
    text: Red Hat Display
  icon:
    logo: fontawesome/solid/b
  palette:
    scheme: default
    features:
      - navigation.footer

plugins:
  - search

copyright: Copyright &copy; 2025 Brett Studer 